### ISSUE TITLE
HA and/or horizontal scalability support?

### ISSUE THREAD

**Issue by ghostsquad** [graphikDB/graphik#74]
Has this project been designed with high availability and/or horizontal scalability in mind?

**Comment by autom8ter** [comment]
V0.4.0 has no support for HA - I am currently evaluating a raft-based implementation vs introducing a control-plane/event-log service for scaling horizontally 🤔

**Comment by ghostsquad** [comment]
If not natively supported, is data sharding a pattern that could be utilized?

**Comment by autom8ter** [comment]
Sharding is not natively supported but you could run multiple instances and route traffic to instances via client-side sharding logic. I’m looking into supporting sharding natively... in a similar way to Dynamodb & Cassandra.

**Comment by ghostsquad** [comment]
Thank you! If you want to make this issue open or close it, I'm good either way.

**Comment by autom8ter** [comment]
graphikDB has HA/horizontal scalability as of v0.8.0 via raft consensus protocol
